@startuml Freemind

package "Freemind (Java)" {
    [Main] <<freemind.main>>
    [Controllers] <<freemind.controller..>>
    [Modes] <<freemind.modes..>>
    [Views] <<freemind.view..>>
    [Common] <<freemind.common..>>
    [Preferences] <<freemind.preferences..>>
    [Extensions] <<freemind.extensions..>>
    [Swing] <<freemind.swing..>>
}

package "Freemind (Kotlin)" {
    [Adapters between logic and external components] <<freemind.adapters..>>
    [Wrappers around external dependencies] <<freemind.dependencies..>>
}

package "Tests and Accessories" {
    [Freemind Tests] <<tests.freemind..>>
    [Freemind accessories] <<accessories..>>
}

package "Java Libs" {
    [Java Swing] <<javax.swing..>>
    [JAXP] <<javax.xml..>>
    [Java Crypto] <<javax.crypto..>>
    [Java Image I/O API] <<javax.imageio..>>
}

package "Third-party libs" {
    [JSoup] <<org.jsoup..>>
    [JOrtho] <<com.inet.jortho..>>
    [SimplyHTML] <<com.lightdev.app.shtm..>>
    [JIBX] <<org.jibx..>>
    [JGoodies] <<com.jgoodies..>>
    [Core SAX API] <<org.xml.sax..>>
    [Jetbrains Libs] <<org.jetbrains.annotations..>>
}

[Swing] --> [Java Swing]

[Common] --> [Main]
[Common] --> [Modes]
[Common] --> [Controllers]
[Common] --> [Views]
[Common] --> [Freemind Tests]
[Common] --> [Java Swing]
[Common] --> [JIBX]
[Common] --> [JGoodies]

[Controllers] --> [Views]
[Controllers] --> [Common]
[Controllers] --> [Main]
[Controllers] --> [Modes]
[Controllers] --> [Wrappers around external dependencies]
[Controllers] --> [Preferences]
[Controllers] --> [Java Swing]

[Extensions] --> [Main]
[Extensions] --> [Views]
[Extensions] --> [Controllers]
[Extensions] --> [Wrappers around external dependencies]
[Extensions] --> [Modes]
[Extensions] --> [Java Swing]

[Views] --> [Controllers]
[Views] --> [Extensions]
[Views] --> [Freemind accessories]
[Views] --> [Freemind Tests]
[Views] --> [Wrappers around external dependencies]
[Views] --> [Adapters between logic and external components]
[Views] --> [Java Swing]
[Views] --> [Java Image I/O API]
[Views] --> [Modes]
[Views] --> [Main]
[Views] --> [Preferences]
[Views] --> [JOrtho]
[Views] --> [SimplyHTML]

[Preferences] --> [Common]
[Preferences] --> [Main]
[Preferences] --> [Modes]
[Preferences] --> [Adapters between logic and external components]
[Preferences] --> [JGoodies]
[Preferences] --> [Controllers]
[Preferences] --> [Java Swing]

[Modes] --> [Preferences]
[Modes] --> [Controllers]
[Modes] --> [Views]
[Modes] --> [Main]
[Modes] --> [Wrappers around external dependencies]
[Modes] --> [Adapters between logic and external components]
[Modes] --> [Extensions]
[Modes] --> [Common]
[Modes] --> [Java Swing]
[Modes] --> [JAXP]
[Modes] --> [JIBX]
[Modes] --> [Java Image I/O API]
[Modes] --> [JGoodies]

[Main] --> [Preferences]
[Main] --> [Common]
[Main] --> [Views]
[Main] --> [Controllers]
[Main] --> [Modes]
[Main] --> [Wrappers around external dependencies]
[Main] --> [Java Swing]
[Main] --> [JSoup]
[Main] --> [JAXP]
[Main] --> [Java Crypto]
[Main] --> [JOrtho]
[Main] --> [Core SAX API]
[Main] --> [Freemind Tests]

[Adapters between logic and external components] --> [Jetbrains Libs]

[Wrappers around external dependencies] --> [Modes]
[Wrappers around external dependencies] --> [Controllers]
[Wrappers around external dependencies] --> [Main]
[Wrappers around external dependencies] --> [Extensions]
[Wrappers around external dependencies] --> [Jetbrains Libs]
[Wrappers around external dependencies] --> [Java Swing]

@enduml